INSERT INTO users (username) VALUES ('michael');

INSERT INTO regions (region_name, region_alias, level) VALUES ('Chicago', 'chicago', 'local');
INSERT INTO regions (region_name, region_alias, level) VALUES ('Southern California', 'socal', 'regional');

INSERT INTO games (game_name, game_alias) VALUES ('Super Smash Bros. Melee', 'ssbm');
INSERT INTO games (game_name, game_alias) VALUES ('Super Smash Bros. Ultimate', 'ssbu');

INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Fox', 'fox.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Falco', 'falco.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Marth', 'marth.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Sheik', 'sheik.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Jigglypuff', 'jigglypuff.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Captain Falcon', 'captainfalcon.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Princess Peach', 'peach.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Samus', 'samus.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Ice Climbers', 'iceclimbers.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Pikachu', 'pikachu.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Yoshi', 'yoshi.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Luigi', 'luigi.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Ganondorf', 'ganondorf.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Dr. Mario', 'drmario.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Mewtwo', 'mewtwo.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Mario', 'mario.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Bowser', 'bowser.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Ness', 'ness.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Kirby', 'kirby.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Game and Watch', 'gameandwatch.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Donkey Kong', 'donkeykong.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Link', 'link.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Roy', 'roy.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Pichu', 'pichu.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Young Link', 'younglink.png');
INSERT INTO game_characters (character_game, character_name, character_image) VALUES ('ssbm', 'Zelda', 'zelda.png');

INSERT INTO rankings (ranking_region, ranking_game, published, ranking_title, ranking_detail) VALUES (1, 'ssbm', '2019-01-07', 'Fall 2018 Season', 'Panel lead by Unsure.');
INSERT INTO rankings (ranking_region, ranking_game, published, ranking_title, ranking_detail) VALUES (2, 'ssbm', '2018-12-15', 'Summer-Fall 2018', '3 and a half month ranking period.');
INSERT INTO rankings (ranking_region, ranking_game, published, ranking_title, ranking_detail) VALUES (1, 'ssbm', '2018-09-30', 'Summer 2018 Season', 'Pleeba, Nox excluded due to inactivity.');

INSERT INTO players (player_tag) VALUES ('Kels');
INSERT INTO players (player_tag) VALUES ('Michael');
INSERT INTO players (player_tag) VALUES ('ORLY');
INSERT INTO players (player_tag) VALUES ('Fluid');
INSERT INTO players (player_tag) VALUES ('JeffWa');
INSERT INTO players (player_tag) VALUES ('Pleasantries');
INSERT INTO players (player_tag) VALUES ('Azzu');
INSERT INTO players (player_tag) VALUES ('Unsure');
INSERT INTO players (player_tag) VALUES ('Pleeba');
INSERT INTO players (player_tag) VALUES ('Ferociti');
INSERT INTO players (player_tag) VALUES ('TechDeath');
INSERT INTO players (player_tag) VALUES ('Eggy');
INSERT INTO players (player_tag) VALUES ('JustJoe');
INSERT INTO players (player_tag) VALUES ('Skerzo');
INSERT INTO players (player_tag) VALUES ('Hyunnies');
INSERT INTO players (player_tag) VALUES ('S2J');
INSERT INTO players (player_tag) VALUES ('SFAT');
INSERT INTO players (player_tag) VALUES ('Fiction');
INSERT INTO players (player_tag) VALUES ('Westballz');
INSERT INTO players (player_tag) VALUES ('Lucky');
INSERT INTO players (player_tag) VALUES ('ARMY');
INSERT INTO players (player_tag) VALUES ('Captain Faceroll');
INSERT INTO players (player_tag) VALUES ('Squid');
INSERT INTO players (player_tag) VALUES ('Mike Haze');
INSERT INTO players (player_tag) VALUES ('Santiago');
INSERT INTO players (player_tag) VALUES ('Smashdaddy');
INSERT INTO players (player_tag) VALUES ('Zeo');
INSERT INTO players (player_tag) VALUES ('Nut');
INSERT INTO players (player_tag) VALUES ('OkamiBW');
INSERT INTO players (player_tag) VALUES ('MegaXmas');
INSERT INTO players (player_tag) VALUES ('Owl');
INSERT INTO players (player_tag) VALUES ('KoDoRiN');
INSERT INTO players (player_tag) VALUES ('Surfero');
INSERT INTO players (player_tag) VALUES ('Kurv');
INSERT INTO players (player_tag) VALUES ('Zack Fair');
INSERT INTO players (player_tag) VALUES ('null');
INSERT INTO players (player_tag) VALUES ('Shoyo');
INSERT INTO players (player_tag) VALUES ('Trix');
INSERT INTO players (player_tag) VALUES ('Pooch');
INSERT INTO players (player_tag) VALUES ('Q?');

INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (1, 1, 1, 1);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (2, 1, 2, 2);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (3, 1, 3, 3);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (4, 1, 4, 4);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (5, 1, 5, 10);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (6, 1, 6, 6);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (7, 1, 7, 5);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (8, 1, 8, 8);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (9, 1, 9, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (10, 1, 10, 11);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (11, 1, 11, 12);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (12, 1, 12, 9);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (13, 1, 13, 7);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (14, 1, 14, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (15, 1, 15, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (1, 3, 1, 1);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (2, 3, 2, 2);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (3, 3, 3, 3);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (4, 3, 4, 6);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (7, 3, 5, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (6, 3, 6, 5);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (13, 3, 7, 4);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (8, 3, 8, 8);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (12, 3, 9, 9);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (5, 3, 10, 12);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (10, 3, 11, 11);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (11, 3, 12, 10);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (38, 3, 13, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (39, 3, 14, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (40, 3, 15, 15);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (16, 2, 1, 3);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (17, 2, 2, 4);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (18, 2, 3, 11);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (19, 2, 4, 6);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (20, 2, 5, 5);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (21, 2, 6, 2);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (22, 2, 7, 8);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (23, 2, 8, 10);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (24, 2, 9, 9);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (25, 2, 10, 12);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (26, 2, 11, 13);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (27, 2, 12, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (28, 2, 13, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (29, 2, 14, 16);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (30, 2, 15, 18);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (31, 2, 16, 21);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (32, 2, 17, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (33, 2, 18, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (34, 2, 19, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (35, 2, 20, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (36, 2, 21, null);
INSERT INTO player_rankings (player, ranking, rank, previous_rank) VALUES (37, 2, 22, null);

INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (1, 'ssbm', 4, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (1, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (2, 'ssbm', 5, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (3, 'ssbm', 6, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (4, 'ssbm', 9, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (4, 'ssbm', 3, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (5, 'ssbm', 4, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (6, 'ssbm', 8, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (7, 'ssbm', 4, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (7, 'ssbm', 2, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (8, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (9, 'ssbm', 4, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (10, 'ssbm', 7, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (11, 'ssbm', 3, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (11, 'ssbm', 4, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (12, 'ssbm', 7, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (13, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (14, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (15, 'ssbm', 3, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (16, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (16, 'ssbm', 4, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (17, 'ssbm', 5, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (18, 'ssbm', 6, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (19, 'ssbm', 3, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (19, 'ssbm', 9, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (20, 'ssbm', 2, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (20, 'ssbm', 4, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (21, 'ssbm', 8, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (22, 'ssbm', 2, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (23, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (24, 'ssbm', 7, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (25, 'ssbm', 4, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (26, 'ssbm', 7, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (27, 'ssbm', 3, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (27, 'ssbm', 4, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (28, 'ssbm', 10, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (29, 'ssbm', 8, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (29, 'ssbm', 26, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (30, 'ssbm', 14, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (30, 'ssbm', 4, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (31, 'ssbm', 6, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (32, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (33, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (33, 'ssbm', 7, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (34, 'ssbm', 2, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (34, 'ssbm', 1, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (35, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (36, 'ssbm', 9, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (37, 'ssbm', 4, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (38, 'ssbm', 2, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (39, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (40, 'ssbm', 2, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (40, 'ssbm', 4, false);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (41, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (42, 'ssbm', 6, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (43, 'ssbm', 4, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (44, 'ssbm', 4, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (45, 'ssbm', 2, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (46, 'ssbm', 3, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (47, 'ssbm', 3, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (48, 'ssbm', 6, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (49, 'ssbm', 12, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (50, 'ssbm', 9, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (51, 'ssbm', 1, true);
INSERT INTO player_ranking_characters (player_ranking, player_ranking_game, character_played, main) VALUES (52, 'ssbm', 1, true);