INSERT INTO users (username) VALUES ('michael');

INSERT INTO regions (region_name, region_alias, level) VALUES ('Chicago', 'chicago', 'local');
INSERT INTO regions (region_name, region_alias, level) VALUES ('Southern California', 'socal', 'regional');

INSERT INTO games (game_name, game_alias) VALUES ('Super Smash Bros. Melee', 'ssbm');
INSERT INTO games (game_name, game_alias) VALUES ('Super Smash Bros. Ultimate', 'ssbu');

INSERT INTO rankings (ranking_region, ranking_game, published, ranking_title, ranking_detail) VALUES (1, 'ssbm', '2019-01-07', 'Fall 2018 Season', 'Panel lead by Unsure.');
INSERT INTO rankings (ranking_region, ranking_game, published, ranking_title, ranking_detail) VALUES (2, 'ssbm', '2018-12-15', 'Summer-Fall 2018', '3 and a half month ranking period.');
INSERT INTO rankings (ranking_region, ranking_game, published, ranking_title, ranking_detail) VALUES (1, 'ssbm', '2018-09-30', 'Summer 2018 Season', 'Pleeba, Nox excluded due to inactivity.');

INSERT INTO players (player_tag) VALUES ('Kels');
INSERT INTO players (player_tag) VALUES ('Michael');
INSERT INTO players (player_tag) VALUES ('ORLY');
INSERT INTO players (player_tag) VALUES ('Fluid');
INSERT INTO players (player_tag) VALUES ('JeffWa');
INSERT INTO players (player_tag) VALUES ('Pleasantries');
INSERT INTO players (player_tag) VALUES ('Azzu');
INSERT INTO players (player_tag) VALUES ('Unsure');
INSERT INTO players (player_tag) VALUES ('Pleeba');
INSERT INTO players (player_tag) VALUES ('Ferociti');
INSERT INTO players (player_tag) VALUES ('TechDeath');
INSERT INTO players (player_tag) VALUES ('Eggy');
INSERT INTO players (player_tag) VALUES ('JustJoe');
INSERT INTO players (player_tag) VALUES ('Skerzo');
INSERT INTO players (player_tag) VALUES ('Hyunnies');
INSERT INTO players (player_tag) VALUES ('S2J');
INSERT INTO players (player_tag) VALUES ('SFAT');
INSERT INTO players (player_tag) VALUES ('Fiction');
INSERT INTO players (player_tag) VALUES ('Westballz');
INSERT INTO players (player_tag) VALUES ('Lucky');
INSERT INTO players (player_tag) VALUES ('ARMY');
INSERT INTO players (player_tag) VALUES ('Captain Faceroll');
INSERT INTO players (player_tag) VALUES ('Squid');
INSERT INTO players (player_tag) VALUES ('Mike Haze');
INSERT INTO players (player_tag) VALUES ('Santiago');
INSERT INTO players (player_tag) VALUES ('Smashdaddy');
INSERT INTO players (player_tag) VALUES ('Zeo');
INSERT INTO players (player_tag) VALUES ('Nut');
INSERT INTO players (player_tag) VALUES ('OkamiBW');
INSERT INTO players (player_tag) VALUES ('MegaXmas');
INSERT INTO players (player_tag) VALUES ('Owl');
INSERT INTO players (player_tag) VALUES ('KoDoRiN');
INSERT INTO players (player_tag) VALUES ('Surfero');
INSERT INTO players (player_tag) VALUES ('Kurv');
INSERT INTO players (player_tag) VALUES ('Zack Fair');
INSERT INTO players (player_tag) VALUES ('null');
INSERT INTO players (player_tag) VALUES ('Shoyo');
INSERT INTO players (player_tag) VALUES ('Trix');
INSERT INTO players (player_tag) VALUES ('Pooch');
INSERT INTO players (player_tag) VALUES ('Q?');

INSERT INTO player_rankings (player, ranking, rank) VALUES (1, 1, 1);
INSERT INTO player_rankings (player, ranking, rank) VALUES (2, 1, 2);
INSERT INTO player_rankings (player, ranking, rank) VALUES (3, 1, 3);
INSERT INTO player_rankings (player, ranking, rank) VALUES (4, 1, 4);
INSERT INTO player_rankings (player, ranking, rank) VALUES (5, 1, 5);
INSERT INTO player_rankings (player, ranking, rank) VALUES (6, 1, 6);
INSERT INTO player_rankings (player, ranking, rank) VALUES (7, 1, 7);
INSERT INTO player_rankings (player, ranking, rank) VALUES (8, 1, 8);
INSERT INTO player_rankings (player, ranking, rank) VALUES (9, 1, 9);
INSERT INTO player_rankings (player, ranking, rank) VALUES (10, 1, 10);
INSERT INTO player_rankings (player, ranking, rank) VALUES (11, 1, 11);
INSERT INTO player_rankings (player, ranking, rank) VALUES (12, 1, 12);
INSERT INTO player_rankings (player, ranking, rank) VALUES (13, 1, 13);
INSERT INTO player_rankings (player, ranking, rank) VALUES (14, 1, 14);
INSERT INTO player_rankings (player, ranking, rank) VALUES (15, 1, 15);
INSERT INTO player_rankings (player, ranking, rank) VALUES (1, 3, 1);
INSERT INTO player_rankings (player, ranking, rank) VALUES (2, 3, 2);
INSERT INTO player_rankings (player, ranking, rank) VALUES (3, 3, 3);
INSERT INTO player_rankings (player, ranking, rank) VALUES (4, 3, 4);
INSERT INTO player_rankings (player, ranking, rank) VALUES (7, 3, 5);
INSERT INTO player_rankings (player, ranking, rank) VALUES (6, 3, 6);
INSERT INTO player_rankings (player, ranking, rank) VALUES (13, 3, 7);
INSERT INTO player_rankings (player, ranking, rank) VALUES (8, 3, 8);
INSERT INTO player_rankings (player, ranking, rank) VALUES (12, 3, 9);
INSERT INTO player_rankings (player, ranking, rank) VALUES (5, 3, 10);
INSERT INTO player_rankings (player, ranking, rank) VALUES (10, 3, 11);
INSERT INTO player_rankings (player, ranking, rank) VALUES (11, 3, 12);
INSERT INTO player_rankings (player, ranking, rank) VALUES (38, 3, 13);
INSERT INTO player_rankings (player, ranking, rank) VALUES (39, 3, 14);
INSERT INTO player_rankings (player, ranking, rank) VALUES (40, 3, 15);
INSERT INTO player_rankings (player, ranking, rank) VALUES (16, 2, 1);
INSERT INTO player_rankings (player, ranking, rank) VALUES (17, 2, 2);
INSERT INTO player_rankings (player, ranking, rank) VALUES (18, 2, 3);
INSERT INTO player_rankings (player, ranking, rank) VALUES (19, 2, 4);
INSERT INTO player_rankings (player, ranking, rank) VALUES (20, 2, 5);
INSERT INTO player_rankings (player, ranking, rank) VALUES (21, 2, 6);
INSERT INTO player_rankings (player, ranking, rank) VALUES (22, 2, 7);
INSERT INTO player_rankings (player, ranking, rank) VALUES (23, 2, 8);
INSERT INTO player_rankings (player, ranking, rank) VALUES (24, 2, 9);
INSERT INTO player_rankings (player, ranking, rank) VALUES (25, 2, 10);
INSERT INTO player_rankings (player, ranking, rank) VALUES (26, 2, 11);
INSERT INTO player_rankings (player, ranking, rank) VALUES (27, 2, 12);
INSERT INTO player_rankings (player, ranking, rank) VALUES (28, 2, 13);
INSERT INTO player_rankings (player, ranking, rank) VALUES (29, 2, 14);
INSERT INTO player_rankings (player, ranking, rank) VALUES (30, 2, 15);
INSERT INTO player_rankings (player, ranking, rank) VALUES (31, 2, 16);
INSERT INTO player_rankings (player, ranking, rank) VALUES (32, 2, 17);
INSERT INTO player_rankings (player, ranking, rank) VALUES (33, 2, 18);
INSERT INTO player_rankings (player, ranking, rank) VALUES (34, 2, 19);
INSERT INTO player_rankings (player, ranking, rank) VALUES (35, 2, 20);
INSERT INTO player_rankings (player, ranking, rank) VALUES (36, 2, 21);
INSERT INTO player_rankings (player, ranking, rank) VALUES (37, 2, 22);